#!/bin/sh
FAME_API_KEY='f5a6219ada13eeaa7ef88076fc6d4a63312f8304c74d12bd7c5b945ed47306270fabac1415ae57df'
FAME_URL='http://10.1.0.203'

users=$(who | awk '{print $1}'|sort -u)
for user in $users
do
	DISPLAY=:0 sudo -u $user notify-send "ウイルスを検知しました" "検知名(${CLAM_VIRUSEVENT_VIRUSNAME})\nファイルパス($CLAM_VIRUSEVENT_FILENAME)"
	file="/data/malware/$(basename ${CLAM_VIRUSEVENT_FILENAME})"
	mv ${CLAM_VIRUSEVENT_FILENAME} $file
	curl -XPOST -H "X-API-KEY:${FAME_API_KEY}" -F "file=@${file}" -F "groups=admin,*,bro,${CLAM_VIRUSEVENT_VIRUSNAME}" ${FAME_URL}/analyses/
done
